version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-minor-and-patch:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod-minor-and-patch:
        patterns:
          - "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
