# Multi-stage image for roost
# Generated by genproj (docker-container capability, language-aware). Adjust
# for your application.
#
# Stage 1 (build): copies the full source tree, installs dependencies and
# builds the application. Stage 2 (runtime): copies only the build output /
# virtualenv and production dependencies, keeping the final image small.


FROM rust:1-slim AS build
WORKDIR /app
COPY Cargo.toml Cargo.lock* ./
RUN mkdir -p src && echo 'fn main() {}' > src/main.rs \
    && cargo fetch \
    && rm -rf src
COPY src ./src
RUN cargo build --release

FROM rust:1-slim
WORKDIR /app
# Link the GHCR container package to its GitHub repo on push. GHCR auto-links
# the package to nickbrett1/roost so it inherits the
# repo's access (public repo -> public package; no manual visibility step).
LABEL org.opencontainers.image.source=https://github.com/nickbrett1/roost

COPY --from=build /app/target/release/roost /usr/local/bin/roost
EXPOSE 3000


CMD ["roost"]
