//! Minimal serving harness (generated by genproj).
//!
//! Binds `0.0.0.0:3000`, answers `GET /healthz` with `200` and a JSON body, and
//! serves the built frontend from `web/dist`. This is the *harness* genproj
//! guarantees: the container comes up, serves the UI, and passes its own
//! HEALTHCHECK. The wire protocol and business endpoints are yours - replace
//! this file with your application.
//!
//! Deliberately dependency-free (standard library only), so the generated
//! crate's `Cargo.lock` stays valid for `cargo build --locked`.

use std::env;
use std::fs;
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::thread;

const DEFAULT_PORT: u16 = 3000;
const HEALTH_PATH: &str = "/healthz";
// JSON, not a bare "ok": Homepage's `customapi` widget parses the health body
// as JSON, so a plain-text reply makes the dashboard tile error.
const HEALTH_BODY: &str = r#"{"status": "ok"}"#;
const STATIC_DIR: &str = "web/dist";

fn main() {
    let port: u16 = env::var("PORT")
        .ok()
        .and_then(|value| value.parse().ok())
        .unwrap_or(DEFAULT_PORT);
    let listener = match TcpListener::bind(("0.0.0.0", port)) {
        Ok(listener) => listener,
        Err(error) => {
            eprintln!("failed to bind 0.0.0.0:{port}: {error}");
            std::process::exit(1);
        }
    };
    println!("serving {STATIC_DIR} on http://0.0.0.0:{port}");
    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                thread::spawn(move || {
                    if let Err(error) = handle(stream) {
                        eprintln!("request failed: {error}");
                    }
                });
            }
            Err(error) => eprintln!("accept failed: {error}"),
        }
    }
}

fn handle(mut stream: TcpStream) -> std::io::Result<()> {
    let mut reader = BufReader::new(stream.try_clone()?);
    let mut request_line = String::new();
    if reader.read_line(&mut request_line)? == 0 {
        return Ok(());
    }
    // Drain the remaining headers so the client finishes writing.
    let mut line = String::new();
    loop {
        line.clear();
        if reader.read_line(&mut line)? == 0 || line == "\r\n" || line == "\n" {
            break;
        }
    }

    let mut parts = request_line.split_whitespace();
    let method = parts.next().unwrap_or("");
    let target = parts.next().unwrap_or("/");
    let path = target.split('?').next().unwrap_or("/");

    if method != "GET" && method != "HEAD" {
        return respond(
            &mut stream,
            405,
            "text/plain; charset=utf-8",
            b"method not allowed",
        );
    }
    if path == HEALTH_PATH {
        return respond(&mut stream, 200, "application/json", HEALTH_BODY.as_bytes());
    }
    match static_file(path) {
        Some(file) => {
            let body = fs::read(&file)?;
            respond(&mut stream, 200, content_type(&file), &body)
        }
        None => respond(&mut stream, 404, "text/plain; charset=utf-8", b"not found"),
    }
}

/// Resolve a request path to a file under STATIC_DIR, refusing traversal.
fn static_file(path: &str) -> Option<PathBuf> {
    let relative = path.trim_start_matches('/');
    let relative = if relative.is_empty() {
        "index.html"
    } else {
        relative
    };
    let root = Path::new(STATIC_DIR).canonicalize().ok()?;
    let mut candidate = root.join(relative);
    if candidate.is_dir() {
        candidate = candidate.join("index.html");
    }
    let resolved = candidate.canonicalize().ok()?;
    if resolved.starts_with(&root) && resolved.is_file() {
        Some(resolved)
    } else {
        None
    }
}

fn content_type(path: &Path) -> &'static str {
    match path.extension().and_then(|extension| extension.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") | Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        Some("txt") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn respond(
    stream: &mut TcpStream,
    status: u16,
    content_type: &str,
    body: &[u8],
) -> std::io::Result<()> {
    let reason = match status {
        200 => "OK",
        404 => "Not Found",
        405 => "Method Not Allowed",
        _ => "OK",
    };
    let head = format!(
        "HTTP/1.1 {status} {reason}\r\n\
         Content-Type: {content_type}\r\n\
         Content-Length: {}\r\n\
         Connection: close\r\n\r\n",
        body.len()
    );
    stream.write_all(head.as_bytes())?;
    stream.write_all(body)?;
    stream.flush()
}
